/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "app.h"
#include "timebase.h"
#include "stm32l476xx.h"

#define SYSTEM_CLOCK_HZ 4000000u
#define LED_TOGGLE_PERIOD_MS 500u

int main(void){

    timebase_init(SYSTEM_CLOCK_HZ);
    app_init();

    while (1){
        app_update();
    }
}



