/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include "stm32l476xx.h"
#include "bsp_led.h"
#include "timebase.h"

#define SYSTEM_CLOCK_HZ 4000000u
#define LED_TOGGLE_PERIOD_MS 500u

int main(void)
{

    uint32_t last_toggle_ms = 0u;

    timebase_init(SYSTEM_CLOCK_HZ);
    bsp_led_init();

    while (1){

        const uint32_t now_ms = timebase_get_ms();

        if((uint32_t)(now_ms - last_toggle_ms) >= LED_TOGGLE_PERIOD_MS){
            last_toggle_ms += LED_TOGGLE_PERIOD_MS;
            bsp_led_toggle();
        }
    }
}





